version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: on-failure
    expose:
      - 6379
    # ports:
    #   - '8001:8001'
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  cache-init:
    image: redis/redis-stack:latest
    container_name: voter-cache-init
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    command: /data/load-redis.sh cache
    networks:
      - backend
    depends_on:
      cache:
        condition: service_started

  voter-api:
    # build: ./voter-api
    image: voter-api:v1
    container_name: todo-api
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true
